
package br.usp.ime.ccsl.choreos.middleware.proxy.support.webservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-13T19:03:29.645-03:00
 * Generated source version: 2.4.0
 * 
 */
 
public class HelloWorld8081_HelloWorld8081Port_Server{

    protected HelloWorld8081_HelloWorld8081Port_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorld8081Impl();
        String address = "http://localhost:8085/hello";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new HelloWorld8081_HelloWorld8081Port_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
