/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SignalSender */

#ifndef _Included_SignalSender
#define _Included_SignalSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SignalSender
 * Method:    sendSignalByPID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SignalSender_sendSignalByPID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SignalSender
 * Method:    sendSignalByProcessName
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_SignalSender_sendSignalByProcessName
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
