
package multiplication.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MultiplicationWebService", targetNamespace = "http://webservice.multiplication/", wsdlLocation = "http://localhost:8084/petals/services/multiply?wsdl")
public class MultiplicationWebService
    extends Service
{

    private final static URL MULTIPLICATIONWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(multiplication.webservice.MultiplicationWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = multiplication.webservice.MultiplicationWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8084/petals/services/multiply?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8084/petals/services/multiply?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MULTIPLICATIONWEBSERVICE_WSDL_LOCATION = url;
    }

    public MultiplicationWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiplicationWebService() {
        super(MULTIPLICATIONWEBSERVICE_WSDL_LOCATION, new QName("http://webservice.multiplication/", "MultiplicationWebService"));
    }

    /**
     * 
     * @return
     *     returns Multiplication
     */
    @WebEndpoint(name = "MultiplicationPort")
    public Multiplication getMultiplicationPort() {
        return super.getPort(new QName("http://webservice.multiplication/", "MultiplicationPort"), Multiplication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Multiplication
     */
    @WebEndpoint(name = "MultiplicationPort")
    public Multiplication getMultiplicationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.multiplication/", "MultiplicationPort"), Multiplication.class, features);
    }

}
