<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="HelloWorld8081Service" targetNamespace="http://webservice.support.proxy.br.usp.ime/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservice.support.proxy.br.usp.ime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://webservice.support.proxy.br.usp.ime/" version="1.0" xmlns:tns="http://webservice.support.proxy.br.usp.ime/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="sayHello" type="tns:sayHello"/>
<xs:element name="sayHelloResponse" type="tns:sayHelloResponse"/>
<xs:complexType name="sayHello">
<xs:sequence>
<xs:element minOccurs="0" name="yourName" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="sayHelloResponse">
<xs:sequence>
<xs:element minOccurs="0" name="greeting" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:schema>

  </wsdl:types>
  <wsdl:message name="sayHelloResponse">
    <wsdl:part element="tns:sayHelloResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sayHello">
    <wsdl:part element="tns:sayHello" name="parameters">
    </wsdl:part>
  </wsdl:message>

  <wsdl:portType name="HelloWorld8081">
    <wsdl:operation name="sayHello">
      <wsdl:input message="tns:sayHello" name="sayHello">
    </wsdl:input>
      <wsdl:output message="tns:sayHelloResponse" name="sayHelloResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloWorld8081ServiceSoapBinding" type="tns:HelloWorld8081">

    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHello">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sayHello">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayHelloResponse">
        <soap:body use="literal"/>
      </wsdl:output>

    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloWorld8081Service">
    <wsdl:port binding="tns:HelloWorld8081ServiceSoapBinding" name="HelloWorld8081Port">
      <soap:address location="http://localhost:8085/hello"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>