//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.09 at 10:04:28 PM BRT 
//

package br.usp.ime.choreos.nodepoolmanager;

public class Node {

	protected String id;
	protected Integer cpus;
	protected Integer ram;
	protected Integer storage;
	protected String so;
	protected String zone;
	protected String ip;
	protected String hostname;
	protected String image;
	protected Integer state;

	public Node() {
	}

	public Node(NodeRestRepresentation rest) {
		cpus = rest.cpus;
		hostname = rest.hostname;
		id = rest.id;
		image = rest.image;
		ip = rest.ip;
		ram = rest.ram;
		storage = rest.storage;
		so = rest.so;
		zone = rest.zone;
		state = rest.state;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the cpus property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCpus() {
		return cpus;
	}

	/**
	 * Sets the value of the cpus property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setCpus(Integer value) {
		this.cpus = value;
	}

	/**
	 * Gets the value of the ram property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getRam() {
		return ram;
	}

	/**
	 * Sets the value of the ram property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setRam(Integer value) {
		this.ram = value;
	}

	/**
	 * Gets the value of the storage property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getStorage() {
		return storage;
	}

	/**
	 * Sets the value of the storage property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setStorage(Integer value) {
		this.storage = value;
	}

	/**
	 * Gets the value of the so property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSo() {
		return so;
	}

	/**
	 * Sets the value of the so property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSo(String value) {
		this.so = value;
	}

	/**
	 * Gets the value of the zone property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getZone() {
		return zone;
	}

	/**
	 * Sets the value of the zone property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setZone(String value) {
		this.zone = value;
	}

	/**
	 * Gets the value of the ip property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * Sets the value of the ip property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIp(String value) {
		this.ip = value;
	}

	/**
	 * Gets the value of the hostname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHostname() {
		return hostname;
	}

	/**
	 * Sets the value of the hostname property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHostname(String value) {
		this.hostname = value;
	}

	/**
	 * Gets the value of the image property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getImage() {
		return image;
	}

	/**
	 * Sets the value of the image property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setImage(String value) {
		this.image = value;
	}

	/**
	 * Gets the value of the state property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * Sets the value of the state property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setState(Integer value) {
		this.state = value;
	}

	public NodeRestRepresentation getRestRepresentation() {
		NodeRestRepresentation rest = new NodeRestRepresentation();

		rest.cpus = cpus;
		rest.hostname = hostname;
		rest.id = id;
		rest.image = image;
		rest.ip = ip;
		rest.ram = ram;
		rest.storage = storage;
		rest.so = so;
		rest.zone = zone;
		rest.state = state;
		
		return rest;
	}

}
