//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.21 at 12:22:38 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://choreos.ime.usp.br/NodePoolManager/")
package br.usp.ime.choreos.nodepoolmanager;
