
/*
 * 
 */

package br.usp.ime.ccsl.choreos.middleware.roleassignmentservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri May 20 15:52:05 BRT 2011
 * Generated source version: 2.2.5
 * 
 */


@WebServiceClient(name = "RoleAssignmentService", 
                  wsdlLocation = "file:src/main/resources/RoleAssignmentService.wsdl",
                  targetNamespace = "http://middleware.choreos.ccsl.ime.usp.br/RoleAssignmentService") 
public class RoleAssignmentService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://middleware.choreos.ccsl.ime.usp.br/RoleAssignmentService", "RoleAssignmentService");
    public final static QName RoleAssignmentServiceSOAP = new QName("http://middleware.choreos.ccsl.ime.usp.br/RoleAssignmentService", "RoleAssignmentServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/RoleAssignmentService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/resources/RoleAssignmentService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RoleAssignmentService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RoleAssignmentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleAssignmentService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns RoleAssignmentService
     */
    @WebEndpoint(name = "RoleAssignmentServiceSOAP")
    public RoleAssignmentService getRoleAssignmentServiceSOAP() {
        return super.getPort(RoleAssignmentServiceSOAP, RoleAssignmentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleAssignmentService
     */
    @WebEndpoint(name = "RoleAssignmentServiceSOAP")
    public RoleAssignmentService getRoleAssignmentServiceSOAP(WebServiceFeature... features) {
        return super.getPort(RoleAssignmentServiceSOAP, RoleAssignmentService.class, features);
    }

}
