package br.usp.ime.ccsl.choreos.middleware.roleassignmentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.5 Fri May 20 15:52:05 BRT 2011
 * Generated source version: 2.2.5
 * 
 */

@WebService(targetNamespace = "http://roleassignment.middlewarer.choreos.ccsl.ime.usp.br/RoleAssignmentService", name = "RoleAssignmentService")
@XmlSeeAlso( { ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RoleAssignmentService {

    @WebResult(name = "uris", targetNamespace = "", partName = "uris")
    @WebMethod
    public ArrayOfStrings get(@WebParam(partName = "role", name = "role", targetNamespace = "") java.lang.String role);

    @WebResult(name = "responseMessage", targetNamespace = "", partName = "responseMessage")
    @WebMethod(action = "http://middleware.choreos.ccsl.ime.usp.br/RoleAssignmentService/NewOperation")
    public java.lang.String assignRole(
            @WebParam(partName = "role", name = "role", targetNamespace = "") java.lang.String role,
            @WebParam(partName = "uri", name = "uri", targetNamespace = "") java.lang.String uri);
}
