
package br.usp.ime.ccsl.choreos.middleware.roleassignmentservice;

import javax.xml.ws.Endpoint;

import br.usp.ime.ccsl.choreos.middleware.roleassignment.RoleAssignmentServiceImpl;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri May 20 15:52:05 BRT 2011
 * Generated source version: 2.2.5
 * 
 */
 
public class RoleAssignmentService_RoleAssignmentServiceSOAP_Server{

    protected RoleAssignmentService_RoleAssignmentServiceSOAP_Server() throws Exception {
        System.out.println("Starting Server");
                Object implementor = new RoleAssignmentServiceImpl();
        String address = "http://www.example.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new RoleAssignmentService_RoleAssignmentServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
