package ime.usp.br.proxy.support.classes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-13T19:03:29.637-03:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://webservice.support.proxy.br.usp.ime/", name = "HelloWorld8081")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld8081 {

    @WebResult(name = "greeting", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.support.proxy.br.usp.ime/", className = "ime.usp.br.proxy.support.webservice.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.support.proxy.br.usp.ime/", className = "ime.usp.br.proxy.support.webservice.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "yourName", targetNamespace = "")
        java.lang.String yourName
    );
}
