--- !!eu.choreos.monitoring.platform.daemon.datatypes.SingleThresholdSpec
attribute:    cpu_user
comparison:   MAX
limit_value:  90

--- !!eu.choreos.monitoring.platform.daemon.datatypes.SingleThresholdSpec
attribute:    cpu_user
comparison:   MIN
limit_value:  35
