
package calculatorserviceprovider;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdditionService", targetNamespace = "http://CalculatorServiceProvider/", wsdlLocation = "http://localhost:8801/CalculatorWebService?wsdl")
public class AdditionService
    extends Service
{

    private final static URL ADDITIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(calculatorserviceprovider.AdditionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = calculatorserviceprovider.AdditionService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8801/CalculatorWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8801/CalculatorWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADDITIONSERVICE_WSDL_LOCATION = url;
    }

    public AdditionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdditionService() {
        super(ADDITIONSERVICE_WSDL_LOCATION, new QName("http://CalculatorServiceProvider/", "AdditionService"));
    }

    /**
     * 
     * @return
     *     returns CalculatorWebService
     */
    @WebEndpoint(name = "CalculatorWebServicePort")
    public CalculatorWebService getCalculatorWebServicePort() {
        return super.getPort(new QName("http://CalculatorServiceProvider/", "CalculatorWebServicePort"), CalculatorWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorWebService
     */
    @WebEndpoint(name = "CalculatorWebServicePort")
    public CalculatorWebService getCalculatorWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://CalculatorServiceProvider/", "CalculatorWebServicePort"), CalculatorWebService.class, features);
    }

}
