
package calculatorserviceprovider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculatorWebService", targetNamespace = "http://CalculatorServiceProvider/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorWebService {


    /**
     * 
     * @param term1
     * @param term2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "total", targetNamespace = "")
    @RequestWrapper(localName = "operationAdd", targetNamespace = "http://CalculatorServiceProvider/", className = "calculatorserviceprovider.OperationAdd")
    @ResponseWrapper(localName = "operationAddResponse", targetNamespace = "http://CalculatorServiceProvider/", className = "calculatorserviceprovider.OperationAddResponse")
    public int operationAdd(
        @WebParam(name = "term1", targetNamespace = "")
        int term1,
        @WebParam(name = "term2", targetNamespace = "")
        int term2);

}
